version: '3'
services:
  www:
    container_name: app
    build: .
    restart: always
    
    volumes:
      - .:/app
    ports:
      - 7000:7000
    links:
      - db
    environment:
      - PYTHONUNBUFFERED=0
  
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro